table mart_prices
	lineageTag: 5f9ca2f0-28f6-421a-953c-2b5b46783a4a

	measure 'Latest Close' =
			CALCULATE(
			    LASTNONBLANK(mart_prices[close], 1),
			    ALLEXCEPT(mart_prices, mart_prices[ticker])
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0aa9a4a1-abf6-427f-a763-586feee542f6

	column ticker
		dataType: string
		lineageTag: 02ff3d4b-b2ca-49ae-bbcb-8ff03f6c87cc
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: 45ff4d1d-aae6-4d95-b619-55bf5c2a2ea6
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column gics_sector
		dataType: string
		lineageTag: 1c77b1dc-766e-44c2-913e-6a223906a202
		summarizeBy: none
		sourceColumn: gics_sector

		annotation SummarizationSetBy = Automatic

	column trade_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b651e74b-ec84-460e-8d74-8932d4b6c48f
		summarizeBy: none
		sourceColumn: trade_date

		variation Variation
			isDefault
			relationship: 48c1b420-a9f5-42e4-8af6-aca72a17f390
			defaultHierarchy: LocalDateTable_1836987c-f8c8-4488-aa86-be347c78a71a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column close
		dataType: double
		lineageTag: bb808df6-44cc-4fe3-b5a2-ff0f7a59385f
		summarizeBy: sum
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column adj_close
		dataType: double
		lineageTag: 3e346601-f758-4568-9383-6f3b1b9f5386
		summarizeBy: sum
		sourceColumn: adj_close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volume
		dataType: int64
		formatString: 0
		lineageTag: ca5724aa-bab1-42ea-b0d8-fd41aa1b47b2
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	column daily_return
		dataType: double
		lineageTag: 6a6d2e0f-2820-4fb5-b832-61e74052623d
		summarizeBy: sum
		sourceColumn: daily_return

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ma_50
		dataType: double
		lineageTag: ebd60f0e-48d2-4feb-99f8-5822df6ff467
		summarizeBy: sum
		sourceColumn: ma_50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ma_200
		dataType: double
		lineageTag: 7443a3c1-f6f7-4164-b6bd-3e7127dd5ae0
		summarizeBy: sum
		sourceColumn: ma_200

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition mart_prices = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-7405618743944849.9.azuredatabricks.net", "/sql/1.0/warehouses/4dbe468336982c0d", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", Protocol=null]),
				    sp500_Database = Source{[Name="sp500",Kind="Database"]}[Data],
				    gold_Schema = sp500_Database{[Name="gold",Kind="Schema"]}[Data],
				    mart_prices_Table = gold_Schema{[Name="mart_prices",Kind="Table"]}[Data]
				in
				    mart_prices_Table

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

